version: "3.9"

services:

  nginx:
    image: nginx
    container_name: lde.nginx
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
    ports:
      - "80:80"

  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - nginx
    ports:
      - "5433:5432"

  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - nginx
      - postgres
    ports:
      - "8001:80"

  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
       - Authorization__Authority=http://www.alevelwebsite.com:5002
       - ConnectionString=server=www.alevelwebsite.com;port=5433;database=catalog;uid=postgres;password=postgres;
       - PathBase=http://www.alevelwebsite.com:5000
    depends_on:
      - nginx
      - postgres
      - pgadmin4
    ports:
      - "5000:5000"

  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - MvcUrl=http://www.alevelwebsite.com
      - CatalogApi=http://www.alevelwebsite.com:5000
      - BasketApi=http://www.alevelwebsite.com:5003
    depends_on:
      - nginx
      - postgres
      - pgadmin4
      - catalog.api
    ports:
      - "5002:5002"

  web.mvc:
    container_name: lde.web.mvc
    build:
      context: .
      dockerfile: Web/MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - Authorization__Authority=http://www.alevelwebsite.com:5002
      - CallbackUrl=http://www.alevelwebsite.com/
      - CatalogUrl=http://www.alevelwebsite.com:5000/api/v1/catalogbff
      - IdentityUrl=http://www.alevelwebsite.com:5002
      - RedirectUrl=http://www.alevelwebsite.com/signin-oidc
    depends_on:
      - nginx
      - postgres
      - pgadmin4
      - catalog.api
      - identityserver
    ports:
      - "5001:5001"

  redis:
    image: redis
    container_name: lde.redis
    depends_on:
      - nginx
      - postgres
      - pgadmin4
      - catalog.api
      - identityserver
      - web.mvc
    ports:
      - "6380:6379"

  basket.api:
    container_name: lde.basket.api
    build:
      context: .
      dockerfile: Basket/Basket.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=http://www.alevelwebsite.com:5002
      - Redis__Host=www.alevelwebsite.com:6380
      - Redis__CacheTimeout=00:00:10
      - PathBase=http://www.alevelwebsite.com:5003
    depends_on:
      - nginx
      - postgres
      - pgadmin4
      - catalog.api
      - identityserver
      - web.mvc
      - redis
    ports:
      - "5003:5003"

networks:

  dockernet:
    external: true
