version: "3.9"

services:
    nginx:
        container_name: lde.nginx
        image: nginx
        command: ["nginx", '-g', "daemon off;"]
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=http://localhost
            - NGINX_PORT=80

    postgres:
        image: postgres
        container_name: lde.postgres
        environment:
            POSTGRES_PASSWORD: postgres
        depends_on:
            - nginx
        ports:
            - "5433:5432"

    pgadmin4:
        image: dpage/pgadmin4
        container_name: lde.pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: user@domain.com
            PGADMIN_DEFAULT_PASSWORD: postgres
        depends_on:
            - nginx
            - postgres
        ports:
            - "8001:80"

    catalog.api:
        container_name: lde.catalog.api
        build:
            context: .
            dockerfile: Catalog/Catalog.Host/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5000
        depends_on:
            - nginx
            - postgres
            - pgadmin4
        ports:
            - "5000:5000"
